# Generated by Django 3.1.3 on 2021-04-23 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_fare_discount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TRANSACTION',
        ),
    ]
